global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    scrape_interval: 15s
    static_configs:
      - targets: ["kong:8001"]

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node_exporter:9100']
